### ISSUE TITLE
#HELP. Noob here. Been running into this error. Is there a problem with my MAF file or reference (tried hg38) or with installation? Any help is appreciated.

### ISSUE THREAD

**Issue by Vickymj93** [broadinstitute/MAESTRO-probe_designer#1]
python3 /home/vicky2023/MAESTRO-probe_designer/probe_designer/maestro1.py -m /home/vicky2023/MAESTRO-probe_designer/probe_designer/EGFR.maf -o /home/vicky2023/EGFR.txt -r /home/vicky2023/ucsc.hg38.fa --disable_blast
INFO    2023-10-05 10:11:00,517 ProbeDesigner   Running using 0+untagged.10.g1282d58 with arguments:

maf=/home/vicky2023/MAESTRO-probe_designer/probe_designer/EGFR.maf
output=/home/vicky2023/EGFR.txt
reference=/home/vicky2023/ucsc.hg38.fa
probe_length=30
temp=50.0
dg_range=[-18.0, -14.0]
static_length=False
same_strand=False
design_ref=False
disable_blast=True

INFO    2023-10-05 10:11:00,521 ProbeDesigner   Found 16 targets in MAF file
Traceback (most recent call last):
  File "/home/vicky2023/MAESTRO-probe_designer/probe_designer/maestro1.py", line 256, in <module>
    probe_designer()
  File "/usr/local/lib/python3.10/dist-packages/click-8.1.7-py3.10.egg/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/click-8.1.7-py3.10.egg/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.10/dist-packages/click-8.1.7-py3.10.egg/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.10/dist-packages/click-8.1.7-py3.10.egg/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/vicky2023/MAESTRO-probe_designer/probe_designer/maestro1.py", line 235, in probe_designer
    maf_df = process_maf(maf)
  File "/home/vicky2023/MAESTRO-probe_designer/probe_designer/maestro1.py", line 53, in process_maf
    remove_duplicates(maf_df)
  File "/home/vicky2023/MAESTRO-probe_designer/probe_designer/maestro1.py", line 43, in remove_duplicates
    df.drop_duplicates(subset=check_dup_cols, inplace=True)
  File "/usr/local/lib/python3.10/dist-packages/pandas-2.1.0-py3.10-linux-x86_64.egg/pandas/core/frame.py", line 6569, in drop_duplicates
    result = self[-self.duplicated(subset, keep=keep)]
  File "/usr/local/lib/python3.10/dist-packages/pandas-2.1.0-py3.10-linux-x86_64.egg/pandas/core/frame.py", line 6701, in duplicated
    raise KeyError(Index(diff))
KeyError: Index(['chromosome', 'tumor_seq_allele2', 'start_position'], dtype='object')

**Comment by Vickymj93** [comment]
It was indeed due to my reference.fasta file. Changing it to the default hg37 version from broad fixed the issue.
